Перенесено состояние в Redux. Используется React DND
modesov/react-burger pull request #7
Opened 2023-02-23 08:41 UTC by modesov

Перенесено состояние в Redux. Перетаскивание и сортировка ингредиентов с помощью React DND

2023-02-23 10:15 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 

Что понравилось:
- Использовали useCallback
- Хороший codestyle
- Реализовали автоскролл по категориям.

Что необходимо исправить:
- [x] Чтобы юзеру было понятно как добавить ингредиенты в конструктор - добавьте надпись. Например - "Перенесите булки сюда".

- [x] следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой. В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

- [x] со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например. Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers
- [ ] Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-23 10:15 UTC, andryxxa93 commented on src/components/section-ingredients/section-ingredients.js
> +  const detailsIngredient = useSelector(state => state.detailsIngredient);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-02-24 10:00 UTC, modesov commented on src/components/section-ingredients/section-ingredients.js
> +  const detailsIngredient = useSelector(state => state.detailsIngredient);
Здравствуйте! Спасибо за ревью! Спасибо за видео про useSelector. Посмотрел, внедрил. По замечаниям тоже все подправил.

2023-02-24 16:45 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-02-25 08:11 UTC, merged